apiVersion: v2
appVersion: 0.0.0
description: my personal website
name: flipenergy
version: 1.0.0
kubeVersion: ">=1.16.0-0"
dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 2.2.0
