#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  repository: flipenergy/flipenergy
  pullPolicy: Always
  tag: latest

strategy:
  type: RollingUpdate

service:
  main:
    ports:
      http:
        port: 80

ingress:
  main:
    enabled: true
    hosts:
      - host: pleasenoddos.com
        paths:
          - path: /

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi
