image:
  repository: flipenergy/flipenergy
  pullPolicy: Always
  tag: latest

strategy:
  type: RollingUpdate

service:
  main:
    ports:
      http:
        port: 80

ingress:
  main:
    enabled: true
    hosts:
      - host: www.pleasenoddos.com
        paths:
          - path: /
      - host: pleasenoddos.com
        paths:
          - path: /
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi
