image:
  repository: flipenergy/flipenergy
  pullPolicy: Always
  tag: latest

strategy:
  type: RollingUpdate

service:
  main:
    ports:
      http:
        port: 80

ingress:
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-homelab"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - host: www.pleasenoddos.com
        paths:
          - path: /
      - host: pleasenoddos.com
        paths:
          - path: /
    tls:
      - secretName: personal-website-tls
        hosts:
          - pleasenoddos.com
          - www.pleasenoddos.com

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi
